// ============================================================================
//  database.hpp
//  Thin RAII wrapper around the MySQL C client library (libmysql).
//  Centralizes connection management, prepared-style parameterized query
//  helpers (via manual escaping — libmysql's mysql_real_escape_string),
//  and row-to-JSON conversion so controllers stay clean.
// ============================================================================

#pragma once

#include <mysql.h>
#include <string>
#include <vector>
#include <memory>
#include "../lib/simple_json.hpp"

namespace evoting {

// A single row represented as column-name -> string-value. NULL columns
// are represented as an empty optional-like sentinel (see isNull()).
class Row {
public:
    void set(const std::string& col, const std::string& val, bool isNull) {
        values_[col] = val;
        nulls_[col] = isNull;
    }
    std::string get(const std::string& col, const std::string& def = "") const {
        auto valIt = values_.find(col);
        if (valIt == values_.end()) return def;
        // A SQL NULL is stored as an empty string with nulls_[col]=true.
        // Honour the caller's default in that case instead of silently
        // returning "" — important for numeric-looking columns like
        // vote_percentage where NULL should read as "0", not blank.
        auto nullIt = nulls_.find(col);
        if (nullIt != nulls_.end() && nullIt->second) return def;
        return valIt->second;
    }
    bool isNull(const std::string& col) const {
        auto it = nulls_.find(col);
        return it != nulls_.end() ? it->second : true;
    }
    int getInt(const std::string& col, int def = 0) const {
        auto it = values_.find(col);
        if (it == values_.end() || it->second.empty()) return def;
        try { return std::stoi(it->second); } catch (...) { return def; }
    }

private:
    std::map<std::string, std::string> values_;
    std::map<std::string, bool> nulls_;
};

class Database {
public:
    Database();
    ~Database();

    // Reads host/port/user/password/dbname from backend/config.json and
    // opens the connection. Returns false (and logs to stderr) on failure
    // rather than throwing, so main() can print a friendly setup hint.
    bool connect(const std::string& configPath);

    bool isConnected() const { return connected_; }

    // Executes an INSERT/UPDATE/DELETE. Returns true on success.
    // Values in `params` are escaped and substituted for "?" placeholders
    // in `sql`, in order — a minimal but safe parameter-binding style
    // that avoids SQL injection without needing full prepared statements.
    bool execute(const std::string& sql, const std::vector<std::string>& params = {});

    // Executes a SELECT and returns all rows.
    std::vector<Row> query(const std::string& sql, const std::vector<std::string>& params = {});

    // Returns the auto-increment id generated by the last INSERT.
    unsigned long long lastInsertId();

    // Returns the number of rows affected by the last execute().
    unsigned long long affectedRows();

    std::string escapeString(const std::string& input);

private:
    MYSQL* conn_ = nullptr;
    bool connected_ = false;

    std::string bindParams(const std::string& sql, const std::vector<std::string>& params);
};

} // namespace evoting
