// ============================================================================
//  wallet.js
//  MetaMask connection + Ethers.js smart contract interaction layer.
//  Depends on contract-config.js (auto-generated by blockchain/scripts/deploy.js)
//  having already been loaded, which supplies window.CONTRACT_ADDRESS and
//  window.CONTRACT_ABI.
// ============================================================================

const Wallet = (() => {
    let provider = null;
    let signer = null;
    let contract = null;
    let connectedAddress = null;

    const HARDHAT_CHAIN_ID_HEX = "0x539"; // 1337 in hex — matches your MetaMask's

    function isMetaMaskAvailable() {
        return typeof window.ethereum !== "undefined";
    }

    async function connect() {
        if (!isMetaMaskAvailable()) {
            throw new Error("MetaMask is not installed. Please install the MetaMask browser extension to vote.");
        }
        if (typeof window.CONTRACT_ADDRESS === "undefined") {
            throw new Error("Smart contract not deployed yet. Run the Hardhat deploy script first (see README).");
        }

        const accounts = await window.ethereum.request({ method: "eth_requestAccounts" });
        if (!accounts || accounts.length === 0) {
            throw new Error("No account was authorized in MetaMask.");
        }

        await ensureHardhatNetwork();

        provider = new ethers.BrowserProvider(window.ethereum);
        signer = await provider.getSigner();
        connectedAddress = await signer.getAddress();
        contract = new ethers.Contract(window.CONTRACT_ADDRESS, window.CONTRACT_ABI, signer);

        // Keep the UI in sync if the user switches accounts in MetaMask.
        window.ethereum.on("accountsChanged", () => window.location.reload());
        window.ethereum.on("chainChanged", () => window.location.reload());

        return connectedAddress;
    }

    async function ensureHardhatNetwork() {
        try {
            await window.ethereum.request({
                method: "wallet_switchEthereumChain",
                params: [{ chainId: HARDHAT_CHAIN_ID_HEX }]
            });
        } catch (switchError) {
            // 4902 = chain not added to MetaMask yet — add it automatically.
            if (switchError.code === 4902) {
                await window.ethereum.request({
                    method: "wallet_addEthereumChain",
                    params: [{
                        chainId: HARDHAT_CHAIN_ID_HEX,
                        chainName: "Hardhat Localhost",
                        rpcUrls: ["http://127.0.0.1:8545"],
                        nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 }
                    }]
                });
            } else {
                throw switchError;
            }
        }
    }

    function getAddress() {
        return connectedAddress;
    }

    function isConnected() {
        return !!connectedAddress;
    }

    async function getAllCandidatesOnChain() {
        requireContract();
        const raw = await contract.getAllCandidates();
        return raw.map((c) => ({
            id: Number(c.id),
            name: c.name,
            partyName: c.partyName,
            voteCount: Number(c.voteCount)
        }));
    }

    async function hasVoted(address) {
        requireContract();
        return await contract.checkHasVoted(address || connectedAddress);
    }

    // Casts an on-chain vote and returns { txHash, blockNumber }.
    async function castVote(candidateOnChainIndex) {
        requireContract();
        const tx = await contract.vote(candidateOnChainIndex);
        const receipt = await tx.wait();
        return {
            txHash: receipt.hash,
            blockNumber: receipt.blockNumber
        };
    }

    function requireContract() {
        if (!contract) {
            throw new Error("Wallet is not connected yet. Click 'Connect Wallet' first.");
        }
    }

    return { connect, getAddress, isConnected, isMetaMaskAvailable, getAllCandidatesOnChain, hasVoted, castVote };
})();
