// ============================================================================
//  scripts/deploy.js
//  Deploys the EVoting contract to whatever network Hardhat is pointed at
//  (by default: localhost, i.e. `npx hardhat node`), then automatically
//  writes ../frontend/js/contract-config.js with the deployed address and
//  ABI — so the frontend never needs manual copy-pasting after a deploy.
//
//  Run with:
//      npx hardhat run scripts/deploy.js --network localhost
// ============================================================================

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("==================================================");
  console.log(" Deploying EVoting smart contract...");
  console.log("==================================================");

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // Election window: opens immediately, runs for 7 days by default.
  // Change these values (or call setVotingStatus/redeploy) to match your
  // real election schedule.
  const nowSeconds = Math.floor(Date.now() / 1000);
  const startTime = nowSeconds;
  const endTime = nowSeconds + 7 * 24 * 60 * 60; // +7 days

  const EVoting = await hre.ethers.getContractFactory("EVoting");
  const evoting = await EVoting.deploy("General Election 2026", startTime, endTime);
  await evoting.waitForDeployment();

  const contractAddress = await evoting.getAddress();
  console.log("EVoting deployed to:", contractAddress);

  // ---- Seed a few sample candidates so the demo works immediately -------
  const sampleCandidates = [
    { name: "Aarav Sharma", party: "Progress Alliance" },
    { name: "Priya Verma", party: "Unity Front" },
    { name: "Rohan Mehta", party: "Independent" }
  ];

  for (const c of sampleCandidates) {
    const tx = await evoting.addCandidate(c.name, c.party);
    await tx.wait();
    console.log(`  Added candidate: ${c.name} (${c.party})`);
  }

  // Open voting immediately so the demo is fully clickable right after deploy.
  const openTx = await evoting.setVotingStatus(true);
  await openTx.wait();
  console.log("Voting is now OPEN.");

  // ---- Auto-generate frontend/js/contract-config.js ----------------------
  const artifact = await hre.artifacts.readArtifact("EVoting");

  const configContent = `// ============================================================================
//  contract-config.js
//  AUTO-GENERATED by blockchain/scripts/deploy.js — do not edit by hand.
//  Regenerated every time you run:
//      npx hardhat run scripts/deploy.js --network localhost
// ============================================================================

const CONTRACT_ADDRESS = "${contractAddress}";

const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};

// Exposed as globals for the vanilla-JS frontend (no bundler required).
window.CONTRACT_ADDRESS = CONTRACT_ADDRESS;
window.CONTRACT_ABI = CONTRACT_ABI;
`;

  const outPath = path.join(__dirname, "..", "..", "frontend", "js", "contract-config.js");
  fs.writeFileSync(outPath, configContent, "utf8");
  console.log("Wrote frontend config to:", outPath);

  console.log("==================================================");
  console.log(" Deployment complete.");
  console.log(" Contract address:", contractAddress);
  console.log(" Open frontend/index.html and connect MetaMask to");
  console.log(" the Hardhat localhost network (chainId 31337) to vote.");
  console.log("==================================================");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
